'use strict';
// Simulação autoritativa do cooperativo. Não depende de DOM, GPU ou pacotes npm.
const {randomBytes}=require('node:crypto');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
const random=(a,b)=>a+Math.random()*(b-a);
const COLORS=['#ef683c','#3486ad','#a264bb','#5b9b68'];
const WEAPONS=[
 {capacity:24,damage:29,interval:.22,reload:1.15,pellets:1,spread:.004,range:40,color:COLORS[0]},
 {capacity:8,damage:19,interval:.72,reload:1.55,pellets:7,spread:.095,range:13,color:COLORS[1]},
 {capacity:40,damage:15,interval:.085,reload:1.35,pellets:1,spread:.023,range:34,color:COLORS[2]}
];
const TYPES=[
 {hp:70,speed:2.1,r:.55,h:1.85,damage:10,points:100},
 {hp:43,speed:3.15,r:.38,h:1.9,damage:8,points:125},
 {hp:180,speed:1.35,r:.8,h:1.85,damage:19,points:200},
 {hp:95,speed:1.7,r:.5,h:1.95,damage:12,points:175}
];
// x, y, z, largura, altura, profundidade. Mesma arena do index.html.
const BOXES=[[-21,0,-21,42,4.7,1],[-21,0,20,42,4.7,1],[-21,0,-20,1,4.7,40],[20,0,-20,1,4.7,40],
 [-8,0,-5,4,2.8,3],[5,0,3,3.3,2.6,3.5],[7.7,0,4.8,2.1,1.6,2.4],[-14,0,7,4.7,1.1,6],[7,0,-13,5,1.25,4],
 [-3,0,9,4,.8,2.1],[12,0,10,2.2,2.1,3],[-15,0,-14,3.6,2,3.3],[-13,2,-13.7,2.3,1.8,2.6],
 [-1,0,-14,1.1,.8,6],[13,0,-4,1,.8,7],[-13,0,0,4,.6,1.9],[2,0,13,6,1,4]].map(([x,y,z,w,h,d])=>({x,y,z,w,h,d}));
function canStand(x,z,r=.34,y=0){return x-r>=-20&&x+r<=20&&z-r>=-20&&z+r<=20&&!BOXES.some(o=>y<o.y+o.h-.02&&y+1.65>o.y&&x+r>o.x&&x-r<o.x+o.w&&z+r>o.z&&z-r<o.z+o.d);}
function move(b,dx,dz,r=.34,y=0){if(canStand(b.x+dx,b.z,r,y))b.x+=dx;if(canStand(b.x,b.z+dz,r,y))b.z+=dz;}
function rayBox(origin,dir,min,max,limit=100){let near=0,far=limit,n=[0,0,0];for(let k=0;k<3;k++){if(Math.abs(dir[k])<1e-7){if(origin[k]<min[k]||origin[k]>max[k])return null;}else{let a=(min[k]-origin[k])/dir[k],b=(max[k]-origin[k])/dir[k],sign=-1;if(a>b){[a,b]=[b,a];sign=1;}if(a>near){near=a;n=[0,0,0];n[k]=sign;}far=Math.min(far,b);if(near>far)return null;}}return near>=0&&near<=limit?{t:near,n}:null;}
function worldRay(o,d,limit=100){let hit=null,best=limit;for(const b of BOXES){const h=rayBox(o,d,[b.x,b.y,b.z],[b.x+b.w,b.y+b.h,b.z+b.d],best);if(h&&h.t<best){best=h.t;hit={...h,pos:o.map((v,i)=>v+d[i]*h.t)};}}if(d[1]<-.0001){const t=-o[1]/d[1];if(t>0&&t<best)hit={t,n:[0,1,0],pos:o.map((v,i)=>v+d[i]*t)};}return hit;}
function clearPath(a,b){const len=distance(a,b);return len<.01||!worldRay([a.x,1,a.z],[(b.x-a.x)/len,0,(b.z-a.z)/len],len);}
const cell=(x,z)=>clamp(Math.floor(z+20),0,39)*40+clamp(Math.floor(x+20),0,39);
const blocked=new Uint8Array(1600);for(let z=0;z<40;z++)for(let x=0;x<40;x++)blocked[z*40+x]=canStand(x-19.5,z-19.5,.82)?0:1;
function flowFor(target){const f=new Int16Array(1600);f.fill(-1);let start=cell(target.x,target.z);if(blocked[start]){let best=Infinity;for(let i=0;i<1600;i++)if(!blocked[i]){const d=Math.hypot(i%40-19.5-target.x,Math.floor(i/40)-19.5-target.z);if(d<best){best=d;start=i;}}}const q=new Int16Array(1600);let a=0,b=1;q[0]=start;f[start]=0;while(a<b){const i=q[a++],x=i%40,z=(i/40)|0;for(const [dx,dz]of [[-1,0],[1,0],[0,-1],[0,1]]){const nx=x+dx,nz=z+dz;if(nx<0||nx>=40||nz<0||nz>=40)continue;const n=nz*40+nx;if(!blocked[n]&&f[n]<0){f[n]=f[i]+1;q[b++]=n;}}}return f;}
const emptyInput=()=>({forward:0,side:0,sprint:false,fire:false,active:false,weapon:0,yaw:0,pitch:0});
class Room {
 constructor(code){this.code=code;this.players=new Map();this.owner=null;this.phase='lobby';this.wave=0;this.score=0;this.kills=0;this.time=0;this.epoch=0;this.enemies=[];this.projectiles=[];this.events=[];this.decals=[];this.eventId=0;this.enemyId=0;this.projectileId=0;this.intermission=0;this.flowTimer=0;this.created=Date.now();}
 addPlayer(name){if(this.players.size>=4)throw Error('Esta sala está cheia (4/4).');const slot=COLORS.findIndex((_,i)=>![...this.players.values()].some(p=>p.slot===i));const id=randomBytes(8).toString('hex');const p={id,token:randomBytes(24).toString('hex'),name:String(name||'Artista').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,18)||'Artista',slot,color:COLORS[slot],x:(slot-1.5)*1.3,y:0,z:-1,yaw:0,pitch:0,vy:0,grounded:true,hp:100,weapon:0,ammo:WEAPONS.map(w=>w.capacity),reload:0,cooldown:0,invuln:1,score:0,kills:0,input:emptyInput(),seq:-1,jumpSeq:0,reloadSeq:0,shotSeq:0,pendingJump:false,pendingReload:false,pendingShot:false,lastInput:this.time,lastSeen:Date.now(),connected:true,flow:null};if(this.phase==='playing'||this.phase==='dead')p.hp=0;this.players.set(id,p);if(!this.owner)this.owner=id;this.event('notice',{text:p.name+' entrou na mesa.'});return p;}
 removePlayer(id){const p=this.players.get(id);if(!p)return;this.players.delete(id);if(this.owner===id)this.owner=this.players.keys().next().value||null;this.event('notice',{text:p.name+' saiu da mesa.'});}
 event(type,data={}){const e={id:++this.eventId,type,time:this.time,...data};this.events.push(e);if(this.events.length>220)this.events.shift();return e;}
 addDecal(pos,n,color,size){const d={pos:pos.map((v,i)=>v+n[i]*.014),n,color,size,angle:random(0,Math.PI*2)};this.decals.push(d);if(this.decals.length>160)this.decals.shift();return d;}
 start(id){if(id!==this.owner)throw Error('Só o líder da sala pode iniciar a partida.');if(this.phase==='playing')throw Error('A partida já está em andamento.');this.epoch++;this.phase='playing';this.wave=0;this.score=0;this.kills=0;this.enemies=[];this.projectiles=[];this.decals=[];this.events=[];this.intermission=0;for(const p of this.players.values()){this.revive(p);p.score=0;p.kills=0;p.input=emptyInput();p.input.weapon=p.weapon;p.pendingShot=false;p.pendingJump=false;p.pendingReload=false;}this.nextWave();}
 revive(p){p.x=(p.slot-1.5)*1.3;p.z=-1;p.y=0;p.vy=0;p.hp=100;p.invuln=2;p.grounded=true;p.ammo=WEAPONS.map(w=>w.capacity);p.reload=0;p.cooldown=0;}
 input(id,packet){const p=this.players.get(id);if(!p)return;const seq=packet.seq;if(!Number.isSafeInteger(seq)||seq<=p.seq)return;p.seq=seq;p.lastInput=this.time;p.lastSeen=Date.now();const finite=(v,f=0)=>Number.isFinite(v)?v:f;p.input={forward:clamp(finite(packet.forward),-1,1),side:clamp(finite(packet.side),-1,1),sprint:packet.sprint===true,fire:packet.fire===true,active:packet.active===true,weapon:clamp(Math.floor(finite(packet.weapon)),0,2),yaw:finite(packet.yaw)% (Math.PI*2),pitch:clamp(finite(packet.pitch),-1.35,1.35)};for(const [key,flag]of [['jumpSeq','pendingJump'],['reloadSeq','pendingReload'],['shotSeq','pendingShot']])if(Number.isSafeInteger(packet[key])&&packet[key]>p[key]){p[key]=packet[key];p[flag]=true;}}
 nextWave(){this.wave++;this.intermission=0;this.projectiles=[];for(const p of this.players.values()){if(p.hp<=0)this.revive(p);p.flow=flowFor(p);}const connected=[...this.players.values()].filter(p=>p.connected);const n=connected.length;const base=this.wave===1?3:this.wave===2?5:8+(this.wave-3)*3;const count=Math.min(60,base+Math.max(0,n-1)*(2+Math.floor(this.wave/3)));for(let i=0;i<count;i++){let kind=0;if(this.wave>=2&&i%3===1)kind=1;if(this.wave>=3&&i%4===2)kind=2;if(this.wave>=4&&i%5===3)kind=3;this.spawn(kind);}this.event('wave',{wave:this.wave,count:this.enemies.length});}
 spawn(kind){const t=TYPES[kind],targets=[...this.players.values()].filter(p=>p.connected&&p.hp>0);if(!targets.length)return;let pos=null;for(let i=0;i<400;i++){const p={x:random(-18.5,18.5),z:random(-18.5,18.5)};if(canStand(p.x,p.z,t.r+.05)&&targets.every(t=>distance(p,t)>8)&&targets.some(t=>t.flow[cell(p.x,p.z)]>=0)){pos=p;break;}}if(!pos){for(let i=0;i<1600;i++){const p={x:i%40-19.5,z:Math.floor(i/40)-19.5};if(canStand(p.x,p.z,t.r+.05)&&targets.every(t=>distance(p,t)>5)&&targets.some(t=>t.flow[i]>=0)){pos=p;break;}}}if(!pos)return;const hp=t.hp*(1+Math.min(this.wave-1,20)*.065)*(1+(targets.length-1)*.12);this.enemies.push({id:++this.enemyId,...pos,kind,hp,maxhp:hp,flash:0,hop:0,attack:random(.5,1.5),phase:random(0,6.28),kx:0,kz:0});}
 shoot(p){const w=WEAPONS[p.weapon];if(p.hp<=0||p.cooldown>0||p.reload>0||p.ammo[p.weapon]<=0)return;p.ammo[p.weapon]--;p.cooldown=w.interval;const o=[p.x,p.y+1.6,p.z],rays=[];let hitCount=0;for(let i=0;i<w.pellets;i++){const yaw=p.yaw+random(-w.spread,w.spread),pitch=p.pitch+random(-w.spread,w.spread),d=[Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)];let wall=worldRay(o,d,w.range),range=wall?wall.t:w.range,target=null;for(const e of this.enemies){if(e.hp<=0)continue;const t=TYPES[e.kind],h=rayBox(o,d,[e.x-t.r,.1,e.z-t.r],[e.x+t.r,t.h,e.z+t.r],range);if(h&&h.t<range){range=h.t;target=e;}}const pos=o.map((v,i)=>v+d[i]*range);let decal=null;if(target){hitCount++;const damage=p.weapon===1?w.damage*Math.max(.35,1-range/20):w.damage;target.hp-=damage;target.flash=.13;target.hop=.16;target.kx+=d[0]*2;target.kz+=d[2]*2;if(target.hp<=0){const pts=TYPES[target.kind].points;this.score+=pts;this.kills++;p.score+=pts;p.kills++;decal=this.addDecal([target.x,.012,target.z],[0,1,0],w.color,TYPES[target.kind].r*2);this.event('kill',{player:p.id,kind:target.kind,points:pts,x:target.x,z:target.z,color:w.color});}}else if(wall)decal=this.addDecal(pos,wall.n,w.color,random(.23,.44)*(p.weapon===1?.7:1));rays.push({pos,hit:!!target,decal});}this.enemies=this.enemies.filter(e=>e.hp>0);this.event('shot',{player:p.id,weapon:p.weapon,origin:o,color:w.color,rays,hits:hitCount});}
 hurt(p,amount){if(p.hp<=0||p.invuln>0)return;p.hp=Math.max(0,p.hp-amount);p.invuln=.42;this.event('hurt',{player:p.id,amount,hp:p.hp});if(p.hp===0){p.reload=0;p.input.fire=false;this.event('down',{player:p.id,name:p.name});}}
 tick(dt){this.time+=dt;this.events=this.events.filter(e=>this.time-e.time<2);if(this.phase!=='playing')return;const living=[...this.players.values()].filter(p=>p.hp>0&&p.connected);if(![...this.players.values()].some(p=>p.connected))return;if(!living.length){this.phase='dead';this.projectiles=[];this.event('over',{wave:this.wave,score:this.score});return;}
  for(const p of living){p.cooldown=Math.max(0,p.cooldown-dt);p.invuln=Math.max(0,p.invuln-dt);const input=p.input,active=input.active&&this.time-p.lastInput<.8;p.yaw=input.yaw;p.pitch=input.pitch;if(p.weapon!==input.weapon){p.weapon=input.weapon;p.reload=0;p.cooldown=Math.max(p.cooldown,.17);}if(p.reload>0){p.reload=Math.max(0,p.reload-dt);if(!p.reload){p.ammo[p.weapon]=WEAPONS[p.weapon].capacity;this.event('reload',{player:p.id});}}if(active&&p.pendingReload&&p.reload<=0&&p.ammo[p.weapon]<WEAPONS[p.weapon].capacity)p.reload=WEAPONS[p.weapon].reload;p.pendingReload=false;
   if(active&&p.pendingJump&&p.grounded){p.vy=6.3;p.grounded=false;}p.pendingJump=false;const forward=active?input.forward:0,side=active?input.side:0,norm=Math.max(1,Math.hypot(forward,side));let speed=input.sprint?6.6:4.4;if(p.reload>0)speed*=.75;move(p,(Math.sin(p.yaw)*forward+Math.cos(p.yaw)*side)/norm*speed*dt,(Math.cos(p.yaw)*forward-Math.sin(p.yaw)*side)/norm*speed*dt,.34,p.y);const oldY=p.y;p.vy-=15*dt;const nextY=p.y+p.vy*dt;let landing=0;for(const b of BOXES)if(p.x+.3>b.x&&p.x-.3<b.x+b.w&&p.z+.3>b.z&&p.z-.3<b.z+b.d&&oldY>=b.y+b.h-.03&&nextY<=b.y+b.h)landing=Math.max(landing,b.y+b.h);if(nextY<=landing){p.y=landing;p.vy=0;p.grounded=true;}else{p.y=nextY;p.grounded=false;}if(active&&(input.fire||p.pendingShot))this.shoot(p);p.pendingShot=false;
  }
  this.flowTimer-=dt;if(this.flowTimer<=0){for(const p of living)p.flow=flowFor(p);this.flowTimer=.45;}
  for(const e of this.enemies){const t=TYPES[e.kind];e.flash=Math.max(0,e.flash-dt);e.hop=Math.max(0,e.hop-dt);e.attack-=dt;let target=null,best=Infinity;for(const p of living)if(p.hp>0){const d=distance(e,p);if(d<best){best=d;target=p;}}if(!target)continue;const p=target,d=best,direct=clearPath(e,p);let vx=0,vz=0;if(d>.9&&(e.kind!==3||d>9||!direct)){let tx=p.x,tz=p.z;if(!direct&&p.flow){const ix=clamp(Math.floor(e.x+20),0,39),iz=clamp(Math.floor(e.z+20),0,39);let best=Infinity;for(let oz=-1;oz<=1;oz++)for(let ox=-1;ox<=1;ox++){const nx=ix+ox,nz=iz+oz;if(nx<0||nx>=40||nz<0||nz>=40)continue;const f=p.flow[nz*40+nx];if(f<0)continue;if(ox&&oz&&(blocked[iz*40+nx]||blocked[nz*40+ix]))continue;const px=nx-19.5,pz=nz-19.5,cost=f+Math.hypot(px-e.x,pz-e.z)*.25;if(cost<best){best=cost;tx=px;tz=pz;}}}const len=Math.hypot(tx-e.x,tz-e.z)||1;vx=(tx-e.x)/len;vz=(tz-e.z)/len;}else if(e.kind===3&&d<5&&d>.01){vx=(e.x-p.x)/d;vz=(e.z-p.z)/d;}for(const other of this.enemies){if(other===e)continue;const dd=distance(e,other),desired=t.r+TYPES[other.kind].r;if(dd<desired&&dd>.01){vx+=(e.x-other.x)/dd*(desired-dd)*2;vz+=(e.z-other.z)/dd*(desired-dd)*2;}}const speed=t.speed*(1+Math.min(this.wave-1,18)*.035);move(e,(vx*speed+e.kx)*dt,(vz*speed+e.kz)*dt,t.r);e.kx*=Math.exp(-9*dt);e.kz*=Math.exp(-9*dt);if(d<t.r+.65&&p.y<1.4&&e.attack<=0&&direct){this.hurt(p,t.damage);e.attack=.8;}if(e.kind===3&&d<18&&direct&&e.attack<=0){const dy=p.y+1.2-1.3,len=Math.hypot(p.x-e.x,dy,p.z-e.z);this.projectiles.push({id:++this.projectileId,x:e.x,y:1.3,z:e.z,vx:(p.x-e.x)/len*7,vy:dy/len*7,vz:(p.z-e.z)/len*7,life:4});e.attack=2.2;}}
  for(const p of this.projectiles){const v=[p.vx,p.vy,p.vz],len=Math.hypot(...v),hit=worldRay([p.x,p.y,p.z],v.map(n=>n/len),len*dt);if(hit){p.life=0;const decal=this.addDecal(hit.pos,hit.n,COLORS[2],.4);this.event('splat',{decal});}else{p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.life-=dt;for(const target of living)if(target.hp>0&&Math.hypot(p.x-target.x,p.z-target.z)<.6&&p.y>target.y&&p.y<target.y+1.85){this.hurt(target,12);p.life=0;break;}}}this.projectiles=this.projectiles.filter(p=>p.life>0);
  if(![...this.players.values()].some(p=>p.connected&&p.hp>0)){this.phase='dead';this.projectiles=[];this.event('over',{wave:this.wave,score:this.score});return;}
  if(this.enemies.length===0&&this.intermission===0){this.intermission=5;this.score+=this.wave*100;for(const p of living)if(p.hp>0)p.hp=Math.min(100,p.hp+20);this.projectiles=[];this.event('clear',{wave:this.wave,bonus:this.wave*100});}if(this.intermission>0){this.intermission-=dt;if(this.intermission<=0)this.nextWave();}
 }
 snapshot(){const round=v=>Math.round(v*1000)/1000;return {code:this.code,owner:this.owner,phase:this.phase,epoch:this.epoch,time:round(this.time),wave:this.wave,score:this.score,kills:this.kills,intermission:round(this.intermission),eventId:this.eventId,players:[...this.players.values()].map(p=>({id:p.id,name:p.name,slot:p.slot,color:p.color,connected:p.connected,x:round(p.x),y:round(p.y),z:round(p.z),yaw:round(p.yaw),pitch:round(p.pitch),vy:round(p.vy),grounded:p.grounded,hp:p.hp,weapon:p.weapon,ammo:p.ammo,reload:round(p.reload),score:p.score,kills:p.kills,seq:p.seq})),enemies:this.enemies.map(e=>({id:e.id,x:round(e.x),z:round(e.z),kind:e.kind,hp:round(e.hp),maxhp:round(e.maxhp),flash:round(e.flash),hop:round(e.hop),phase:e.phase})),projectiles:this.projectiles.map(p=>({id:p.id,x:round(p.x),y:round(p.y),z:round(p.z)})),events:this.events};}
}
module.exports={Room,BOXES,WEAPONS,TYPES,COLORS,canStand,rayBox,worldRay};
